### ISSUE TITLE
using redux dev tool

### ISSUE THREAD

**Issue by omidfi** [redux-loop/redux-loop#101]
Hi,
I'm trying to add redux dev tool alongside this and can't figure out how to do it. 

The dev tools doc asks to change this: 

```javascript 
 const store = createStore(reducer, preloadedState, 
    window.__REDUX_DEVTOOLS_EXTENSION__ &&   window.__REDUX_DEVTOOLS_EXTENSION__()
  );
```
with: 
```javascript
 const store = createStore(reducer, preloadedState, 
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
  );
```

However with redux-loop our createStore looks like this: 
```javascript
import { install } from 'redux-loop';
import reducer from './reducer';

export default createStore(reducer, null, install());
```

Redux is new to me so my question might hurt your eyes, sorry :)

**Comment by sebinsua** [comment]
From the [`redux`](http://redux.js.org/docs/api/createStore.html) docs:

> To apply multiple store enhancers, you may use [`compose()`](http://redux.js.org/docs/api/compose.html).

Therefore, you will want something like this:

```js
import { createStore, compose } from 'redux'
import { install } from 'redux-loop';
import reducer from './reducer';

export default createStore(
  reducer,
  null, 
  compose(
    install(),
    window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : v => v
);
```

**Comment by omidfi** [comment]
Thanks a lot @sebinsua it solved my problem
