### ISSUE TITLE
Redux Saga and Loop

### ISSUE THREAD

**Issue by kirkstrobeck** [redux-loop/redux-loop#105]
http://stackoverflow.com/questions/41704984/redux-saga-and-loop

**Comment by MichalZalecki** [comment]
Isn't that like trying to integrate `superagent` with `axios`? You could write an adapter as saga's actions are easy to differentiate but I don't think that this is problem on which maintainers should focus.

**Comment by lukewestby** [comment]
@kirkstrobeck i'm afraid this is a common difficulty that people have when using multiple enhancers more broadly than just redux-loop. unfortunately I won't be able to fix this as a redux-loop-specific thing but i can offer the advice of trying to play with the order of your enhancers in createStore, even if it means you need to call `applyMiddleware` more than once. see if it works with redux-loop applied after the redux-saga middleware and before. if neither get you what you need i'm afraid you'll be stuck with the situation. although, redux-loop does expose a `getModel` function which should at least at some readability to the process of pulling out the state
