### ISSUE TITLE
[Question] Explain lift

### ISSUE THREAD

**Issue by RomeroDiver** [redux-loop/redux-loop#107]
Hi,
I can't seem to understand what **Effects.lift** is for? Could anyone explain on a kind of real-life example?

I would greatly appreciate that, thanks!

**Comment by quarryman** [comment]
The same question. Effects.lift probably needs a good example of usage to get the idea of why should one want to take affect from nested action in order to apply it to higherOrderAction.

**Comment by lukewestby** [comment]
Agreed! New work is being done in #110 and we'll make sure there are good docs and an example by the time 3.0.0 gets published.

In the mean tine I can offer a quick example here. The gist is that if `combineReducers` is giving you a headache (and so you are aware it is being removed in the next version) you can still nest your reducers for a particular property in a larger state object. When you do that, you'll want to make sure that you are capturing all of the effects for that nested reducer under a single action in the top reducer:

```
const nestedReducer = (state, action) => {
  switch (action.type) {
    ONE:
      return loop({ ...state, hello: action.hello }, Effects.promise(Api.nestedOne))
    TWO:
      return loop({ ...state, world: action.world }, Effects.promise(Api.nestedTwo))
    default:
      return loop(state, Effects.none)
  }
}

// This is the reducer that gets passed to `createStore`
const topReducer = (state, action) => {
  switch (action.type) {
    case NESTED:
      const [ nestedState, nestedEffect ] = nestedReducer(state.nestedState, action.nestedAction)
      return loop(
        { ...state, nestedState },
        Effects.lift(nestedEffect, (a) => ({ type: 'NESTED', nestedAction: a }))
     )
  }
}
```

So as effects are flowing upward from the nested reducer, the actions they ultimately result in will be bundled up in another action which your top reducer knows how to interpret so they can be passed back down to your nested reducer once again.
