### ISSUE TITLE
3.1.0 Ideas

### ISSUE THREAD

**Issue by lukewestby** [redux-loop/redux-loop#112]
- #108 - Implement `equals` for Effects so people don't have to mess around with their own deep-equality checks in tests. (Should obey [Setoid](https://github.com/fantasyland/fantasy-land#setoid) laws)

**Comment by bdwain** [comment]
Passing action creators to Effects (like the Cmd implementation we came up with here https://github.com/redux-loop/redux-loop/issues/66)

**Comment by lukewestby** [comment]
@bdwain i just pushed up a commit to add a `catch` function to effects, so now you can get this functionality by combining `map` and `catch`

```
effect(Api.someCallWithoutActionCreators, arg1, arg2)
  .map(Actions.onSuccess)
  .catch(Actions.onFailure)
```
