### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by mboperator** [redux-loop/redux-loop#116]
Hey!

I just wanted to drop a quick thank you here for this phenomenal side effect library. We're using `redux-loop` in a huge number of our production applications at [Procore Technologies](https://www.procore.com/) and I've personally found it to be superior to `redux-sagas` when it comes to scaling side effect complexity.

So thanks again for the amazing work. Looking forward to v3.0. Let me know if there's any way I can help.

**Comment by mboperator** [comment]
Also I'm looking at the new docs and I love how you've simplified the API to just `map` and `fromLazyPromise`. I'm not a huge fan of the method name `fromLazyPromise` though. 

I understand that it's explicit but after a developer implements it once it becomes kind of a handful to type.

**Comment by lukewestby** [comment]
Hey! Thank you so much for the kind words. I love when people let me know where they're using it, it's inspiration to keep things moving! I actually have a day off tomorrow from regular work so I'm going to be writing documentation for v3 and then preparing the release.

We actually moved a little bit past `fromLazyPromise` in the new setup. As of the official release API there will be one function called `effect` that does the same thing `fromLazyPromise` does. Additionally, we're exporting the `Effect` type as a TypeScript interface that has `map`, `catch`, `toPromise`, and `equals`, so it provides just enough flexibility to accommodate different testing and calling styles using the default implementation returned by the `effect` function, and also lets you roll your own Effect implementation.

I've been writing about [using the Freer Monad in JS](https://www.humblespark.com/blog/extensible-effects-in-node-part-1), so I'm planning to take advantage of this additional flexibility in that way.

Thanks!
