### ISSUE TITLE
No readme on npm

### ISSUE THREAD

**Issue by ashishsc** [redux-loop/redux-loop#118]
Hello there,
I know that you guys are working on the 3.0 release, but I'm a little confused which set of documentation I'm supposed to be looking at.

https://www.npmjs.com/package/redux-loop has no README right now and the neither the examples in the  examples directory nor the example inline in the README of the master branch seem to work. What's the recommended way to install / use redux loop?

**Comment by bdwain** [comment]
I'll definitely update this. Thanks!

**Comment by bdwain** [comment]
3.0 is released and has a readme. Thanks again!
