### ISSUE TITLE
Are folks using this with prism? How do I scope actions in redux-loop?

### ISSUE THREAD

**Issue by jcheroske** [redux-loop/redux-loop#124]
I've spent the last few days experimenting with the `prism` library. I'm really liking the concept of composing action types. I'm wondering if anyone here has experience using both `redux-loop` and `prism` together. If not, does redux-loop offer a way to compose actions as well?

**Comment by MichalZalecki** [comment]
@jcheroske Have you hit any wall when trying to integrate `redux-loop` and `prism`? `redux-loop` is focused on "purifying" side effects not how you model your state.

**Comment by jcheroske** [comment]
No, haven't even used redux-loop yet. But I'm trying to put the pieces in place to have a true fractal architecture, and I'm at the point of choosing a side effect lib to work with my prism implementation. With prism and some modifications, I now have the ability to create component/reducer modules that are scoped in both state and action, allowing for what seems to be good reusability so far. But at this point, everything I've done has been sync. Now I need to bring in the complex effects while maintaining scope.

**Comment by MichalZalecki** [comment]
If your solution requires some deep integration it can be easier to write your own middleware as a compatibility layer. It's [quite simple](http://michalzalecki.com/reduce-side-effects-in-react-redux/#middleware-and-room-for-improvement). All in all prism helps you to create scoped reducer which still should be able to return both state and effects so you should be fine.

**Comment by bdwain** [comment]
Hi @jcheroske 

Sorry it's been so long since you've heard back. I'm going to be taking over maintenance of redux-loop. The first thing I want to get is get an update out and get the documentation up to date with the latest version on npm. After that, I'd be happy to work on improving redux-loop's integration with other libraries.
