### ISSUE TITLE
Upcoming Changes

### ISSUE THREAD

**Issue by bdwain** [redux-loop/redux-loop#130]
Sorry for the long delay between updates everyone. 

I released a version 3.0 that should solve some of the problems with version 2. You can see the details [here](https://github.com/redux-loop/redux-loop/releases/tag/v3.0.0). It's not a huge departure from version 2, and I think it should set us up to make more improvements to the project.

There's still a few things I would like to address quickly before working on new features.
- [x] v2 backwards compatibility
- [x] Typescript Typings (if anyone has any experience with this and is interested in helping, that would be appreciated)
- [x] Rewrite tests in jasmine or mocha
- [x] Update build tasks

After those are done, I think we'll be in a good position to start improving the API more based on feedback from people who are using it.

**Comment by ashishsc** [comment]
I think the question about TS support is whether we should just define typings or rewrite the library in typescript itself. One is larger endeavor than the other obviously.

**Comment by bdwain** [comment]
I think for now it'd be good to just do typings since that seems to be in high demand and I'd rather not keep people waiting anymore. 

I think it's worth discussing if we want to rewrite everything in typescript. I'm not sure I see a big benefit from it. But I don't have much experience with it so I'd be interested in hearing other peoples' opinions.

**Comment by ashishsc** [comment]
I agree that we should just do the typings in the short term. The benefit of a typescript rewrite are the same as any project: it eliminates having to

- maintain a seperate typings file (I would hope)
- write classes of unit tests checking for the correct type since the compiler will catch these

And in addition, it will make it easier for us to
- refactor the codebase in the future
- have new developers come on (reading the type signatures is helpful, same as jsdoc)

**Comment by bdwain** [comment]
that makes sense. well i guess if we are going to rewrite the tests and build process anyway, may as well do full typescript conversion before we do those.

**Comment by ashishsc** [comment]
For reference:
https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

I'm going to read this tomorrow

**Comment by gyzerok** [comment]
There was already new API fully rewritten in TypeScript. I suggest to use it, because it simplifies library quite a lot and got a lot of thought in it. It was planned as 4.0.

**Comment by MazeChaZer** [comment]
@gyzerok I am currently using that API in my TypeScript project, works great :+1:

**Comment by bdwain** [comment]
I know there were plans for a few different rewrites of the API, but all of them were pretty drastic and would have required existing users to completely rewrite what they had. Since they were never published to npm, I thought it would be best to release a less drastic change so that existing users of the latest published version had a clear migration path. I also think the version that I released solves most of the same problems that were trying to be solved in the other rewrites while still maintaining some similarity with what was released before.

I definitely do not intend for the current release to be a final API in any way. We can still make improvements to it, including ideas proposed in the typescript rewrite. I just think we need to be mindful of people currently using redux-loop when we do, and that the version I released is the best starting point for those changes.

**Comment by gyzerok** [comment]
Yeah, I see what you mean. That do definitely make sense.

Next major release could contain breaking changes. The idea behind TypeScript rewrite was to provide the bare minimum API. Then the development could be done in a way heavily inspired by Elm. Put a lot of thought into changes and see if it does really make sense to make API larger.

Also one of the ideas was to move away from Elm-specific stuff. Like `Cmd`, for example. They do make sense for you if you come from Elm, however they do not make any sense if you come from JavaScript. Since this library is intended mostly for JavaScript devs learning curve for them should be smoother.

Going this way we can ensure that we introduce breaking changes (if any) very slow. And there are a lot of design process put in them. So people won't need to migrate very often and if they do thats for good.

**Comment by bdwain** [comment]
Yea i agree about focusing on making this clear to non-elm users, since the elm users will be fine either way. Though I think the name Cmd is fine as long as we explain it in as much detail as we would if we called it something else. It just has the added benefit of being especially easy to pick up if you are familiar with elm.

One thing i've been thinking about to ease the migration more to v3 is to add back Effects temporarily (with console warnings), and they could just wrap the Cmd api. For example:

```js
Effects.promise = function(func, ...args){
   console.warn('Effects.promise is deprecated. Please switch to Cmd.run');
   return Cmd.run(func, {
       args,
       successActionCreator: action => action,
       failActionCreator: action => action
   });
}
```

Could do something similar with Effects.call. The other ones idk if we need as much since they can just be fixed with find and replace. 

I would want to remove these wrappers in v4 but this way there's a full major version before a deprecated API is removed.

**Comment by icopp** [comment]
I'd personally propose replacing the `Cmd.x` functions with individual exports with names like `queuePromise` and `queueDispatch`. Similarly, `Cmd.getState` and `Cmd.dispatch` would probably be better as something like `getStatePlaceholder` and `dispatchPlaceholder`.

On a side note, I'm considering using this in a large Typescript project I'm working on, so if I do I'll be submitting a typings file sooner or later.

**Comment by bdwain** [comment]
thank you for the suggestion @icopp. Can you please post it in #133 ? I set up that issue to discuss changes for version 4.0. 

For the immediate future I'd like to focus on typescript support and build/test improvements because those are currently preventing people from using the library and contributing to it. Once those are done I think we'll be in a good spot to make a lot of API improvements.

**Comment by willisplummer** [comment]
👋 We've been using v2 of redux-loop for a while at work and we've been writing and maintaining our own declarations for the previous API. I'd be happy to take a pass at writing some type definitions for v3 if no one has started looking into this.

![bitmoji](https://render.bitstrips.com/v2/cpanel/10218279-166716282_8-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by bdwain** [comment]
@willisplummer yes that would be much appreciated. I've been meaning to add them but I have no experience with typescript and haven't had the chance to learn it yet.

**Comment by willisplummer** [comment]
👍 will try to get a PR open before the long weekend. thanks for all your work on this project!

**Comment by bdwain** [comment]
Just wanted to post an update here. 

Typescript typings have been added to the library. Thank you @willisplummer for your hard work on that. It is much appreciated.

I think considering we have the typescript support now, rewriting the entire library in typescript might not be worth the effort at this point. If there's a demand for it later, we can reevaluate. But it'd take a lot of time compared to the benefits it would provide and I'd rather not hold up new feature development.

I'm going to release a version 4.0 soon which updates the build process and tests to be similar to redux. Tape will be replaced with jest and we'll have proper module support in our builds. It will also remove the deprecated functionality available in v3 (Effects and Cmd.call, constant, arbitrary and promise).

After that, I think we can look at all new feature development and release major changes as necessary.

**Comment by bdwain** [comment]
#148 is open

**Comment by bdwain** [comment]
Closing this as everything is done and 4.0 is released. Thanks everyone!

**Comment by willisplummer** [comment]
congrats!
