### ISSUE TITLE
5.0 Ideas

### ISSUE THREAD

**Issue by bdwain** [redux-loop/redux-loop#133]
The Cmd API released in version 3 was the first attempt at simplifying the API and making effects more reusable. But there are still more improvements that can be made. Let's use this thread to post feedback on the current version and ways to improve it. 

- New Cmd types like batch and sequence, except they dispatch resulting actions as they become ready instead of all at once at the end.
- Break out integrations with popular libraries into separate projects (such as immutablejs-optimized combineReducers)
- Expose a method to help nest reducers (like combineReducers but where the common parent has functionality of its own).

**Comment by icopp** [comment]
I'd personally propose replacing the `Cmd.x` functions with individual exports with names like `queuePromise` and `queueDispatch`. Similarly, `Cmd.getState` and `Cmd.dispatch` would probably be better as something like `getStatePlaceholder` and `dispatchPlaceholder`.

There's also the issue that `loop` as a name for the function to return is kind of weird, since in the common parlance it's not actually looping anything; that's what got me thinking of names using terminology like `queue` in the first place.

**Comment by ashishsc** [comment]
I guess at some point we should decide if we want to try and mimic elm's function names or not. Task and Effect? `thunk` ? `schedule` ?

**Comment by icopp** [comment]
"Thunk" seems like a bad idea, given that in this space it tends to mean `redux-thunk` pretty specifically.

**Comment by bdwain** [comment]
i'm not married to any particular name, but i'd want to not change them without evidence that Cmd was confusing people or that a new name would be much more clear

**Comment by farism** [comment]
I like having things be the same as elm. I kind of think of redux-loop as an elm polyfill for redux and should strive to match the implementation as closely as possible. With additional features as necessary, of course.

That said, configurable batching behavior would probably be at the top of the list in terms of features I would like to see. A parallel batch would be nice, which @bdwain already mentioned in the first comment.

**Comment by bdwain** [comment]
Version 4.0 was just released. It was a small update to remove deprecated functionality and clean up the build and tests to make future changes easier. 

Now that that's done, I'd love to start tackling some of these ideas and coming up with more. 

The first one I'd like to do is configurable batching behavior. My thought is that we have batch and sequence now, but it'd probably be simplest for there to be one Cmd type for an array of Cmds, with 2 options available. Option 1 is a boolean to choose batch vs sequence (parallel vs series) behavior. Option 2 is to determine whether all actions dispatch at once at the end (the current behavior) or each action gets dispatched as it becomes ready.

I'm not married to any particular name, but I was thinking of calling it Cmd.array or Cmd.set and deprecating Cmd.batch and sequence. I'd rather not deprecate things again if possible, but I think it'd be confusing because I think option 2 should be called batch (and be off by default, which is not the current behavior). Option 1 can be called sequence and be off by default.

If we did that, we could release the new Cmd with a minor version bump and add deprecation warnings for batch and sequence in 4.0 and remove them in 5.0.

Thoughts?

**Comment by bdwain** [comment]
#151  was made to address the batching issue.

**Comment by bdwain** [comment]
Release 4.1.0 with the new batching changes.

**Comment by bdwain** [comment]
I opened #153 to address the remaining two points. I'm going to close this issue as there's not much discussion anymore and all of the original ideas have been implemented.
