### ISSUE TITLE
Making originalAction an array to trace effect history

### ISSUE THREAD

**Issue by Marswang92** [redux-loop/redux-loop#136]
Shall we provide `originalActions` as an array instead of just the previous action to trace the history of side effect? Also it will provide a way for `redux-logger` to nicely log all the history side effects.

**Comment by bdwain** [comment]
are you referring to this file? https://github.com/redux-loop/redux-loop/blob/master/modules/errors.js

**Comment by Marswang92** [comment]
@bdwain yep but more about the [install.js](https://github.com/redux-loop/redux-loop/blob/master/modules/install.js) file. I've made a rough implementation here

https://github.com/Marswang92/redux-loop/commit/5e1fbfa58db6a2b4b0925a5f8820ede86ae265a7

**Comment by bdwain** [comment]
i'm not sure I follow. Each side effect is triggered by a single action anyway. Where does the array of actions come from?

**Comment by Marswang92** [comment]
So in my use case there're side effects which are caused by an action which is emitted by another side effects. Use the this repo's example, `Start short increment` is dispatched from the `Cmd.batch` from `Start both increment` and ` Finish short increment` is caused by the side effect from `Start short increment`. It would be quite informative to be able to trace back this whole behavior.

<img width="451" alt="screen shot 2017-08-05 at 8 58 08 pm" src="https://user-images.githubusercontent.com/14301745/29000486-3363baf2-7a21-11e7-92d7-7b25bb1f7272.png">

**Comment by bdwain** [comment]
I think I see. I'm a little confused about the implemntation you linked though. You changed the signature of store.dispatch in there to take an array of actions. That seems like it would be an issue. Wouldn't redux just ignore that action array?

**Comment by Marswang92** [comment]
So the way I'm doing this is taking the advantage of `liftReducer`. Since we don't want to overwrite the `reducer` controlled by `redux`, what we can do is asking `liftReducer` to keep on tracking `originalAction`. When you dispatch the action to `liftReducer` basically it will check if `originalAction` exist or not. If so, just simply append the current action into the array.

**Comment by Marswang92** [comment]
So the way I'm currently use is when you dispatch an action with `cmd`, you'll either create an array of `originalAction` which contains it self or just append it to the array of its `originalActions`. The `dispatch` method inside the `redux-loop` middleware will handle the `originalActions` parameter properly.

**Comment by bdwain** [comment]
hi @Marswang92 . I'm very sorry I haven't responded in so long. I haven't had a ton of time lately. 

If you can get this to work in a branch, I'd be happy to merge it in. I think I see where your rough implementation is going but I haven't been able to think through it completely yet. 

One thing I did notice is that I'm pretty sure when you pass the originalActions array into store.dispatch, it will get ignored. store.dispatch is the underlying dispatch method and not the one that we expose. Other than that, it seems like what you're going for would work.

**Comment by Marswang92** [comment]
Yeah I'll try to spend some time on that maybe this weekend, thx!

**Comment by bdwain** [comment]
Also, just so you're aware, #151 seems like it might have a significant effect on the implementation of this. With Cmd.list, not all actions get dispatched from the install.js file. Unless you have the batch option enabled, the promise from the list cmd is resolved with an empty array.

**Comment by ashishsc** [comment]
Possibly related to #131
