### ISSUE TITLE
TypeScript type definitions for combineReducers

### ISSUE THREAD

**Issue by jaredklewis** [redux-loop/redux-loop#145]
Hello. Currently, redux-loop uses the the following types for its `combineReducers` implementation:

```typescript
export interface ReducerMapObject<T, A extends Action> {
  [key: string]: LoopReducer<T, A>;
}

export interface LiftedLoopReducer<S, A extends Action> {
  (state: S | undefined, action: AnyAction): Loop<S, A>;
}

declare function combineReducers<S, T>(
  reducers: ReducerMapObject<T, AnyAction>
): LiftedLoopReducer<S, AnyAction>;
```

In effect, this means that it is only possible to use  `combineReducers` if all the reducers return a state with the same interface. Consider the example below:

```typescript
interface AppState {
    foo: FooState;
    bar: BarState;
}

interface FooState {
    foo: string;
}

interface BarState {
    bar: string;
}

function reduceFoo (state: FooState = { foo: "foo" }, action): Loop<FooState, AnyAction>  {
    // contents of reducer not relevant to example
    return state;
}

function reduceBar (state: BarState = { bar: "bar" }, action): Loop<BarState, AnyAction>  {
    // contents of reducer not relevant to example
    return state;
} 

combineReducers<AppState, any>({
  foo: reduceFoo,
  bar: reduceBar
});
```

In this situation, TypeScript will given an error unless `combinedReducers`'s second parameterized type is set to `any` (or an otherwise sufficiently vague type), in which case it provides no type safety. 

The problem is that the current `ReducerMapObject` requires that all the mapped reducers have an identical type signature, which is incompatible with the basic idea of `combineReducers`: combining different functions that reduce _different parts_ of the parent state.

I think the solution here is use a mapped type as follows:

```typescript
// EDIT: forgot LoopReducer first time around
type ReducerMapObject<S> = { [K in keyof S]: LoopReducer<S[K], AnyAction> };

declare function combineReducers<S>(
  reducers: ReducerMapObject<S>
): LiftedLoopReducer<S, AnyAction>;
```

I am happy to make a PR for this issue, but first wanted to gather feedback.

Please let me know if I should make a PR for this issue. Thanks.

**Comment by bdwain** [comment]
Thanks for pointing this out! It does seem like an issue. I think your solution makes sense, but I'm wondering why Redux doesn't seem to follow that pattern. Their definitions look like this.

```ts
export interface ReducersMapObject {
  [key: string]: Reducer<any>;
}

export function combineReducers<S>(reducers: ReducersMapObject): Reducer<S>;
```

so they don't seem to provide any type safety.

As far as your proposed solution, one question I have is why the map object needs the second parameter at all. it's not currently using it. 

cc @willisplummer thoughts on this? have you run into this using the new types?

**Comment by jaredklewis** [comment]
As for my solution, sorry for the mistake. I totally botched it actually. I think it needs to be more like this:

```typescript
type ReducerMapObject<S> = {
    [K in keyof S]?: LoopReducer<S[K], AnyAction>;
};
```

The above definition also relaxes the requirement for every store key to be present, which allows you to handle some sub-stores outside of `combineReducers` (if you need to get fancy for some sub stores).

As for the difference with redux, it's because mapped types require typescript 2.1 (released around 1 year ago). Redux has updated their rulings to 2.1+ in the @next release (redux 4

I think the `redux-loop` being

**Comment by jaredklewis** [comment]
As for my solution, sorry for the mistake. I totally botched it actually. I think it needs to be more like this:

```typescript
type ReducerMapObject<S> = {
    [K in keyof S]?: LoopReducer<S[K], AnyAction>;
};
```

The above definition also relaxes the requirement for every store key to be present, which allows you to handle some sub-stores outside of `combineReducers` (if you need to get fancy for some sub stores).

As for the difference with redux, it's because mapped types require typescript 2.1 (released around 1 year ago). Redux has updated their rulings to 2.1+ in the @next release (redux 4

I think the `redux-loop` being

**Comment by willisplummer** [comment]
the thinking behind the current type definition of `combineReducers` is that `T` was a union type of all of the sub-states of the combined reducers. That approach definitely can get pretty boilerplate heavy as you start to add more and more unions though.

This solution looks very promising to me. Thanks for the suggestion!

**Comment by bdwain** [comment]
Have you run into a scenario where not requiring all sub stores would be useful. I'm hesitant to do something odd like that without good reason, and combinereducers shouldn't ever need its children to be split. I'd imagine if there was a good reason to do it redux would have done it in theirs too. 

Either way I think the fix is worth it. If you want to open a pr that would be awesome!

@willisplummer  if you could look at the Pr also that would be great since I haven't done much with the typescript stuff yet.

**Comment by willisplummer** [comment]
+1 regarding the optional substores - an example would be really helpful 🙏

**Comment by jaredklewis** [comment]
Hi guys, I made a PR. Decided not to have the optional sub stores so that our type definition matches the redux next branch one as closely as possible.
