### ISSUE TITLE
Cmd's silently failing

### ISSUE THREAD

**Issue by te-chris** [redux-loop/redux-loop#156]
Hi, first, let me qualify that I'm new to using `redux-loop`, so maybe I'm missing something.

I've got a standard setup, have tried putting `install()` at the top and the bottom of my composed enhancers, but nothing is ever being run.

When I use a `Cmd.action`, e.g., this is added to the state:
```
{
      type: 'ACTION',
      actionToDispatch: {
        type: 'USER_LOGIN_SUCCESS'
      }
}
```

But the actual side effect is never dispatched. When I tried to use `Cmd.run`, nothing is ever actually run. 

Here's my store:
```
import {createStore, applyMiddleware, compose} from 'redux';
import {routerMiddleware} from 'react-router-redux';
import createHistory from 'history/createBrowserHistory';
import rootReducer from './reducers/root';
import {install} from 'redux-loop';

export const history = createHistory();

const initialState = {};
const enhancers = [];
const middleware = [routerMiddleware(history)];

if (process.env.NODE_ENV === 'development') {
  const devToolsExtension = window.devToolsExtension;

  if (typeof devToolsExtension === 'function') {
    enhancers.push(devToolsExtension());
  }
}

const composedEnhancers = compose(
  install(),
  applyMiddleware(...middleware),
  ...enhancers
);

const store = createStore(
  rootReducer,
  initialState,
  composedEnhancers
);

export default store;
```

Here's my reducer:
```
import {
  USER_LOGIN_TRIGGER,
  USER_LOGIN_SUCCESS,
  userLoginSuccess
} from '../actions/user';
import {loop, Cmd} from 'redux-loop';

const DEFAULT_STATE = {
  session: false,
};

export default (state = DEFAULT_STATE, action) => {
  switch(action.type) {
    case USER_LOGIN_TRIGGER:
      return loop(
        {...state},
        Cmd.action(userLoginSuccess()));
    case USER_LOGIN_SUCCESS:
      return {
        ...state,
        loggedIn: true
      };
    default:
      return state;
  }
};
```

Thanks :)

**Comment by bdwain** [comment]
Hi. Two things stand out to me that may be related.

- You should use undefined for the initialState param to createStore. By using an object, the top level reducer won't use its default state if it has one.
- It looks like you're using the devtools incorrectly:

> Note that starting from v2.7, window.devToolsExtension was renamed to window.__REDUX_DEVTOOLS_EXTENSION__ / window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__.

I think you want to use it like this 

```js
import ...
import {compose} from 'redux';

let composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__  || compose;
const storeEnhancer = composeEnhancers(
    install(),
    applyMiddleware(...)
);
const store = createStore(reducer, undefined, storeEnhancer);
```

You can also check the NODE_ENV if you want to avoid running it in prod, but it's usually fine to leave in prod.

One other question is if `import rootReducer from './reducers/root';` is the reducer you linked or if that is just one of your reducers? It's important to use redux-loop's combineReducers wherever your reducers nest (assuming you have more than one)

**Comment by te-chris** [comment]
Thanks for getting back to me so quickly!

It was `combineReducers` :) I was still using redux's one. works perfectly now.

**Comment by bdwain** [comment]
Cool glad i could help. Also just FYI on the trigger action you shoild not be doing {...state}. Just use state. The spread operator is going to create a shallow copy even though you're not actually changing anything and that will cause extra rerenders in your app. In general you should only create a new object if you are changing it.

**Comment by te-chris** [comment]
Thank you, good catch.
