### ISSUE TITLE
Replace readme with a multi-page guide 

### ISSUE THREAD

**Issue by bdwain** [redux-loop/redux-loop#158]
The top-level readme is getting bloated trying to explain every feature. It'd be great to have a more comprehensive guide and leave the readme to be a high level explanation and some links.

A gitbook would be cool, but maybe unnecessary considering redux-loop is a relatively small library. 
I think long term, we'll want one though.

At the very least the docs folder could be expanded upon to have pages that are focused on specific topics or concepts.

**Comment by bdwain** [comment]
i set up gitbooks for the project. I'm gonna play around with that for a bit and get a js.org domain to host it on.

**Comment by on3iro** [comment]
Sounds great. I was actually thinking that we should spread the word about this awesome library a bit more. So maybe creating some kind of logo would be cool as well. Unfortunately I am not a designer so, I can't really do that, but I could ask some friends.

If you need support with the docs, let me know :)

**Comment by bdwain** [comment]
hm there is a logo and i thought it was in the readme. I guess not. We should add it back. 

And yes I've been meaning to work on the docs but haven't had the time. If you're interested in making a PR to add some docs that would be very much appreciated (if so, don't worry about the gitbook for now. Markdown files are fine and can be converted to a gitbook easily).

**Comment by on3iro** [comment]
@bdwain sounds good to me. I will see if I can find some spare time over the next week to work on the docs :)

**Comment by psbanka** [comment]
I'm also interested in working on this and I think I have some spare time to contribute in the next few days, @on3iro – hit me up if you'd like to work on this together?

**Comment by on3iro** [comment]
@psbanka cool. Looks like you already put some work into this :) Unfortunately I am on vacation the next two days, but could help out on saturday. Just hit me up if there is anything I can help you with.

**Comment by bdwain** [comment]
This is complete. Thanks again @psbanka !
