### ISSUE TITLE
Enhancer is not working

### ISSUE THREAD

**Issue by morewings** [redux-loop/redux-loop#165]
Tried to use redux-loop in my project and found a bug. When reducer returns a loop enhancer doesn't catch and handle it, but puts array with new state and action into store.
Here is code I'm using - https://gist.github.com/morewings/4d31e5927063a1901981de3ac59fcdc2

**Comment by bdwain** [comment]
Is the root reducer imported by reducer.js the reducer in the other file or something else? It sounds like you’re using vanilla combine reducers somewhere and not redux loop’s. 

My other thought is to mess with the order of your store enhancers to see if that fixes it. But I think that’s less likely

**Comment by bdwain** [comment]
try rearranging the order of your store enhancers. typically you shouldn't need thunk and promise if you are using loop, so removing those or changing the order around could help.

**Comment by morewings** [comment]
I'm doing it like this
`case MESSAGE.RECEIVE: {
      const messagesLens = lensProp('messages');
      const addMessage = append(action.payload);
      return loop(
        over(messagesLens, addMessage, state),
        Cmd.run(() => {return console.log('test')}),
      );
    }`

**Comment by bdwain** [comment]
i'm not familiar with ramda but don't you want to use the previous state value when calculating the new state?

**Comment by morewings** [comment]
It's like that `over(messagesLens, addMessage, state)` pay attention to last argument. But the problem I'm strugling is not because of Ramda. Redux-loop is not running an action even with plain object as a new state.

**Comment by bdwain** [comment]
can you update the gist? with the reducer and the file that says combineReducers?

**Comment by morewings** [comment]
@bdwain updated.
https://gist.github.com/morewings/4d31e5927063a1901981de3ac59fcdc2#file-reducer-js
https://gist.github.com/morewings/4d31e5927063a1901981de3ac59fcdc2#file-reducers-js

**Comment by bdwain** [comment]
not sure if it matters but that's not how I use the redux devtools extension. I just say 

```js
  let composeEnhancers;
  if(window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__){
    composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__;
  }
  else{
    composeEnhancers = compose;
  }
```

other than that my only thought is that maybe the middleware is affecting it. I haven't seen how promise works. Is it possible to see how it behaves without thunk and promise in there?

**Comment by morewings** [comment]
@bdwain I've removed promise, but it's not possible with thunk (requires a lot of rewriting).
Also tried your way of composing, didn't help.
Thanks anyway.

**Comment by bdwain** [comment]
hm i can look more later. i don't have a ton of time to dig into it right now. if you want to try to debug it, the redux loop code isn't too complicated. i'd set a breakpoint in the dispatch method in install.js
