### ISSUE TITLE
Built working example with create-react-app, redux-loop and TypeScript

### ISSUE THREAD

**Issue by meandmax** [redux-loop/redux-loop#170]
May be interesting for others, had some barriers to setting this up: https://github.com/meandmax/redux-loop-ts-example

**Comment by bdwain** [comment]
sweet! I'll link to this from the readme.

**Comment by bdwain** [comment]
Actually I'll leave this open for now because we there's not really a good spot for it in the current readme, which needs to be broken up into better docs. Once that's done, i'll add this link to that.

**Comment by bdwain** [comment]
This is linked to now on https://redux-loop.js.org/docs/tutorial/Tutorial.html

We can probably do a better job of highlighting typescript support in general, but I'll leave that to separate issues about improving the organization and clarity of the docs overall. Thanks again for creating that example @meandmax !
