### ISSUE TITLE
can you provide an  example about "Normalizing State Shape"

### ISSUE THREAD

**Issue by jiqimaogou** [redux-loop/redux-loop#172]
in most time, we have a nested data structure, redux suggest us "Normalizing State Shape", can  you provide the best practice about "Normalizing State Shape" with redux loop?

**Comment by bdwain** [comment]
It should be pretty much the same as vanilla redux. Redux loop deals more with side effects that happen due to your state changes, which are mostly independent of your state shape. Whether you return `newState` or `loop(newState, Cmd.run(someSideEffect))`, the state shape is pretty much the same.
