### ISSUE TITLE
[Q] Problem implementing a request polling mechanism

### ISSUE THREAD

**Issue by on3iro** [redux-loop/redux-loop#180]
Hey,

I am currently trying to implement some form of request polling mechanism, but I really struggle to do it right with redux-loop.

### What I would like to achieve

I want to initiate a polling-sideeffect by running a cmd.
Upon receiving a cancellation action I want to stop my polling function.

### What is the issue

I am not sure of how to implement the cancellation. I figured there would be multiple ways to do it:

1. the polling function itself could always dispatch an action which runs the cmd again until a flag is set to `true`  - this would basically mean that everything apart from the request logic itself is part of my reducer, but I fear that this might impact performance and will also flood _redux-dev-tools_ with unnecessary polling action messages
2. My first command just initiates the sideEffect and the whole polling mechanism lies outside. Dispatching a cancellation action should then somehow effect this running polling function. This would be my preferred solution, but I can't figure out how to actually cancel the request that way. My first thought was to create a cancellation function within the first run of my polling function and upon resolving handing it to the _redux-loop_ `successActionCreator`, which could than map it to the store. But the redux store should remain fully serializable and that would break it.

It would be super cool if you could point me into some direction of where to go from here.

Thanks in advance

on3iro

**Comment by on3iro** [comment]
Ok I think I just found a way to solve my problem.

I initiate a polling state outside of redux next to my sideeffects and expose a handler to set the state.
My polling function then just checks this state, while I can use redux-loop to run my handlers and e.g. cancel the polling.

**Comment by bdwain** [comment]
Hi. I don't think you need to store state outside of redux if you want to avoid it. You can initiate the polling by running a side effect that calls setInterval or setTimeout. Those return an id, which you can store in your redux state. When you dispatch a cancellation action, just pass that id to a side effect that calls clearInterval/clearTimeout with the id from the state. Here's an example.

```js
//reducer.js
import {startPolling, stopPolling} from './polling-effects';
import {Cmd} from 'redux-loop';

function pollingStartedAction(id){
  return {
    type: 'POLLING_STARTED',
    id
  }
}

const initialState = {
  intervalId: null
};

function reducer(state = initialState, action){
  if(action.type === 'START_POLLING'){
    return loop(state, Cmd.run(startPolling, {successActionCreator: pollingStartedAction}));
  }
  else if(action.type === 'POLLING_STARTED'){
    return {...state, intervalId: action.id};
  }
  else if(action.type === 'CANCEL_POLLING'){
    const newState = {...state, intervalId: null};
    return loop(newState, Cmd.run(stopPolling, {args: [state.intervalId]}));
  }
}

//polling-effects.js
const POLLING_FREQUENCY = 5000; //every 5 seconds
export function startPolling(){
  //makeRequest is the function you want to run regularly
  return setInterval(makeRequest, POLLING_FREQUENCY);
}

export function stopPolling(id){
  clearInterval(id);
}
```

There are other ways you can do it also, but this is the most basic. If your polling behavior is to wait X seconds after the last poll finishes (rather than just poll every X seconds without caring about the previous one) then you'll need to use timeouts instead of intervals and store a new timeout id each time a poll happens. But the general idea is similar.

**Comment by on3iro** [comment]
Hey @bdwain ,

wow thanks for the elaborate answer, I really appreciate that! 👍 
Maybe we could add a recipes section to the docs with examples like this?
This would probably help new users to understand common advanced use cases and how
these problems could be solved with _redux-loop_. Another recipe that comes to mind
would be request queuing (😃 #176 ).

**Comment by bdwain** [comment]
Yea that's a good idea. I've been meaning to do that. We just got the doc site up recently. 

I created #181 to keep track of this for now. If you're interested, feel free to open a PR. I've been busy lately but i'll do it at some point soon when I get the chance.

**Comment by stewartduffy** [comment]
Hi all, I know this is closed and an old issue but was hoping someone could help - awesome example by the way, works nicely.

However, does anyone have any ideas how to update the store based on the response of the poll request? Can an action be dispatched from the startPolling function from polling-effects? 

Thanks

**Comment by bdwain** [comment]
Hi @stewartduffy. Yes you can dispatch from the effect file by passing [Cmd.dispatch](https://redux-loop.js.org/docs/tutorial/AdvancedTopics.html#accessing-state-and-dispatching-actions-from-your-cmds) to your effect. Then it could look something like this.

```js
export function startPolling(){
  //makeRequest is the function you want to run regularly
  return setInterval(() => makeRequest(dispatch), POLLING_FREQUENCY);
}

function makeRequest(dispatch){
  return fetch(url).then(rsp => {
    dispatch(myAction(rsp));
  });
}
```
