### ISSUE TITLE
Found the way of testing whole app flow

### ISSUE THREAD

**Issue by SlavkoPar** [redux-loop/redux-loop#188]
https://github.com/SlavkoPar/sajt

**Comment by bdwain** [comment]
@SlavkoPar I'm not sure what you mean by testing the whole app flow. Can you elaborate please?

**Comment by SlavkoPar** [comment]
We have 2 phases: 
1) Shuffling the cards 
2) Playing

We have the logic inside of reducers, where each action define the next action.

**Phase 1) shuffling**
When we dispatch: Actions.shuffleDeck() we have the flow:
   shuffleDeck -> shuffleDeckSucceed ->  
   repeat actions 10 times: 
      drawTheCard to human -> drawTheCardSucceed
	 repeat actions 3 times:
         drawTheCard to computer -> drawTheCardSucceed
   
   
**Phase 2) playing**
When we dispatch: Actions.playHand() we have the flow:
repeat actions 10 times:
   playHand 
      humanToPlay -> humanToPlaySucceed -> humanPlayed
      repeat actions 3 times:
	 computerToPlay -> computerPlayed
   handPlayed
   find winner of the hand
find winner of the game

**Comment by bdwain** [comment]
Sorry I meant can you elaborate on what this means in the context of Redux Loop? Is there  a change you would like me to add to the documentation? Or a source change? I'm not really following.

**Comment by bdwain** [comment]
Action creators in redux loop are typicallly not async anyway though. 

In general I'm not sure about maintaining the functionality of returning a promise from store.dispatch long term anyway. I don't think it behaves in a predictable way.

**Comment by bdwain** [comment]
you should be able to use async action creators if you set up your middleware correctly. But it's not really specific to redux loop so I'm not sure what we would document. It's documented at the redux site.

**Comment by bdwain** [comment]
I'm going to close this since there's nothing actionable.
