### ISSUE TITLE
Add support for Either along with Promise for Cmd.run

### ISSUE THREAD

**Issue by stereobooster** [redux-loop/redux-loop#193]
The issue with Promise is that result of rejection is untypeable. The idea is to add support for Either.

Example of Either implementations:

- https://github.com/gcanti/fp-ts
- https://github.com/ramda/ramda-fantasy/blob/master/docs/Either.md
- https://github.com/sanctuary-js/sanctuary-either
- https://folktale.origamitower.com/docs/v2.1.0/migrating/from-data.either/

**Comment by bdwain** [comment]
Can't your success action creator just expect an Either? I'm not sure about building that into redux-loop itself. We still need to be able to handle errors if your result throws an error, so I'm not sure we can tie the result of an Either to the failActionCreator anyway

**Comment by stereobooster** [comment]
Yes, good idea to return it as a result of a Promise, it will look a bit odd that success action creator would produce positive and negative results, but will work.
