### ISSUE TITLE
Should Cmd.run work inside Cmd.list?

### ISSUE THREAD

**Issue by danieljharvey** [redux-loop/redux-loop#195]
Hi! Firstly, thanks for everybody's work on this library, it really is the nicest way to deal with effects in Redux.

I've had some issues with success/fail actions not dispatching from a Cmd.run nested inside a Cmd.list. The action creators are run but their results are not dispatched to Redux so therefore the results of side effects just disappear into the void. Before I diagnose and submit a fix, I just want to check this is not intended behaviour in some way?

Thanks!

**Comment by bdwain** [comment]
Hi @danieljharvey. Thanks for filing an issue about this. Can you provide an example something that fails (a gist or a link to a failing project or a snippet of code is fine)

**Comment by danieljharvey** [comment]
Yeah sure, will pull together a small example.

**Comment by danieljharvey** [comment]
On doing so it would appear the issue is not a real issue, therefore I assume we've got some weird custom combineReducers of our own causing the problem instead. Sorry to be a bother.
