### ISSUE TITLE
Add install function's config options to type definitions

### ISSUE THREAD

**Issue by mllustosa** [redux-loop/redux-loop#203]
I just updated to version `4.5.0` and noticed that I cannot use the new config options (when installing the middleware) to add `DONT_LOG_ERRORS_ON_HANDLED_FAILURES`, because it's lacking the proper TS definition.

It would be great if you guys could update the type definitions to allow the use of the option.

Thanks a lot in advance and keep up the great work!

**Comment by bdwain** [comment]
closed via #204
