### ISSUE TITLE
Actions won't compile under TypeScript strict mode

### ISSUE THREAD

**Issue by thomasvanlankveld** [redux-loop/redux-loop#215]
The following won't compile with TypeScript's `strict` flag set to `true`:

```typescript
import { combineReducers } from 'redux-loop';

type Thing = {
  foo: string;
};

type MyAction = {
  type: "FETCH_SUCCESS";
  payload: Thing[];
} | {
  type: "ADD_SUCCESS";
  payload: Thing;
};

function myReducer(state: Thing[] = [], action: MyAction) {
  switch (action.type) {
    case "FETCH_SUCCESS":
      return action.payload;
    case "ADD_SUCCESS":
      return [...state, action.payload];
  }
  return reducerSafety(state, action);
}

function reducerSafety<T>(state: T, action: never): T {
  return state;
}

const rootReducer = combineReducers({
  things: myReducer
});
```

Which yields:

```
Type '(state: Thing[] | undefined, action: MyAction) => Thing[]' is not assignable to type 'LoopReducer<Thing[], AnyAction>'.
  Types of parameters 'action' and 'action' are incompatible.
    Type 'AnyAction' is not assignable to type 'MyAction'.
      Property 'payload' is missing in type 'AnyAction' but required in type '{ type: "ADD_SUCCESS"; payload: Thing; }'.ts(2322)
```

I'd really like to use [typesafe-actions](https://github.com/piotrwitek/typesafe-actions) with tagged union types and strict mode to check exhaustion in my reducers.

**Comment by Eke** [comment]
@thomasvanlankveld Hello, did you manage to fix this somehow?

**Comment by thomasvanlankveld** [comment]
@Eke I tried briefly, but we're using redux-observable for now.

**Comment by bdwain** [comment]
Hi. Do either of you want to make a PR to add support this? I'd be happy to look at it if you did. I'm not exactly sure what is needed to make it work. I don't use typescript myself so I've relied on PR's from people to add support for it.

**Comment by abirmingham** [comment]
It appears that `LoopReducer` needs to be updated from the following (as seen on `5.1.1`):
```typescript
export interface LoopReducer<S, A extends Action> {
  (state: S | undefined, action: AnyAction): S | Loop<S, A>;
}
```
to the following:
```typescript
export interface LoopReducer<S, A extends Action = AnyAction> {
  (state: S | undefined, action: A, ...args: any[]): S | Loop<S, A>;
}
```

Which, oddly, is already contained in the `index.d.ts` file on the master branch. Was there possibly a publishing issue where `index.d.ts` wasn't picked up in the `5.1.1` npm package?

**Comment by bdwain** [comment]
cool! Going to close this then.
