### ISSUE TITLE
TypeScript error on replaceReducer

### ISSUE THREAD

**Issue by Stijnkool** [redux-loop/redux-loop#219]
Hi,

I get a TypeScript error on the `replaceReducer` function of `redux`.
I use the `LoopReducer` type for my reducer. But the `replaceReducer` function requires a general `Reducer`.

Here is the basic createStore example:

```ts
import { compose, createStore } from "redux";
import { install, StoreCreator } from "redux-loop";
import reducer from "./reducer";

const enhancedCreateStore = createStore as StoreCreator;

const store = enhancedCreateStore(
  reducer,
  undefined,
  compose(
    window.__REDUX_DEVTOOLS_EXTENSION__ &&
      window.__REDUX_DEVTOOLS_EXTENSION__(),
    install()
  )
);

// Enable HMR for reducer updates
if (ENV === "development") {
  if (module.hot) {
    module.hot.accept("./reducer", () => {
      store.replaceReducer(reducer);
    });
  }
}
```

I get the following TypeScript error on the `reducer` parameter of `store.replaceReducer`:
`Argument of type 'LoopReducer<State, Action>' is not assignable to parameter of type 'Reducer<State, AnyAction>'.
  Type 'State | [State, CmdType<Action>]' is not assignable to type 'State'.
    Type '[State, CmdType<Action>]' is not assignable to type 'State'.ts(2345)`

This can be easily fixed by the user by just typecasting the `replaceReducer` function:
```ts
type ReplaceReducer = (newReducer: LoopReducer<State, Action>) => void;
const enhancedReplaceReducer = store.replaceReducer as ReplaceReducer;

// Enable HMR for reducer updates
if (ENV === "development") {
  if (module.hot) {
    module.hot.accept("./reducer", () => {
      enhancedReplaceReducer(reducer);
    });
  }
}
```

But I believe having a correct `Store` type returned from the `StoreCreator` is more accurate than just typecasting the `replaceReducer` method. That is why I currently have the following fix in place:

```ts
import {
  Store as ReduxStore,
  StoreEnhancer,
  Action,
  AnyAction,
  DeepPartial,
  createStore as ReduxCreateStore
} from "redux";
import { LoopReducer } from "redux-loop";

export interface Store<S, A extends Action = AnyAction>
  extends ReduxStore<S, A> {
  replaceReducer(nextReducer: LoopReducer<S, A>): void;
}

interface StoreCreator {
  <S, A extends Action>(
    reducer: LoopReducer<S, A>,
    enhancer?: StoreEnhancer<S>
  ): Store<S, A>;
  <S, A extends Action>(
    reducer: LoopReducer<S, A>,
    preloadedState?: DeepPartial<S>,
    enhancer?: StoreEnhancer<S>
  ): Store<S, A>;
}

export const createStore = ReduxCreateStore as StoreCreator;
```
This just extends the standard types from redux. Something that redux-loop already does.
I am not sure If these new types would cause conflicts. But they work fine in my codebase and are very minimal.

Could these new types be included in the library?

**Comment by bdwain** [comment]
this seems reasonable. Would we still be able to import createStore from redux, and just import install from redux-loop?

**Comment by Stijnkool** [comment]
I am unfortunately no longer using this library. This can be closed.
