### ISSUE TITLE
Testing redux-loop action with jest, enzyme and moxios

### ISSUE THREAD

**Issue by Jorgeewa** [redux-loop/redux-loop#220]
Hi guys, I am relatively new to redux loop and I am trying to test my action (integration test) in this way:

     import { appStore } from '../store';
     import moxios from 'moxios';
     ...
     describe('Init', () => {
        beforeEach(() => {
            moxios.install();
        });
    
        afterEach(() => {
            moxios.uninstall();
        });
        test('Store is updated correctly', (done) => {
            const expectedState = {
            }
    
            moxios.wait(() => {
                const request = moxios.requests.mostRecent();
                request.respondWith({
                    status: 200,
                    response: {
                        data: 
                            { 
                                z: [[1, 2], [3, 4]] 
                            }
                    }
                })
            });
            return appStore.dispatch(init('1234567'))
            .then((res: any) => {
                const newState = appStore.getState();
                expect(newState).toBe(expectedState);
            });
            
        });
    });

My reducer looks like this:
`			return loop (
				{...state},
				Cmd.list(callAFunc(action.payload.param, callAnAction))
			);`

Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

Doing `console.log(appStore.dispatch(init('1234567')))` in the test returns a promise but never executes the .then. I know I am doing something wrong and I used this https://redux-loop.js.org/docs/tutorial/Testing.html tutorial for testing my reducer but I need heads up in testing the actions.

**Comment by bdwain** [comment]
your reducer looks incorrect. 

`Cmd.list(callAFunc(action.payload.param, callAnAction))`

Cmd.list takes an array of other cmds. Not sure what callAFunc is but if the parameter passed to Cmd is not an array of other Cmds, nothing will work as expected. It should log a warning though if the parameter is incorrect.

**Comment by bdwain** [comment]
Also keep in mind that the promise returned dispatch is not always going to be super useful. Depending on the Cmds that run, i don't think it's guaranteed to wait to resolve until all actions are done running. I work on a large app and have never used it. I need to reevaluate if it still even makes sense to return a promise given all of the changes that the library has made over the years.
