### ISSUE TITLE
Setting empty object in reducer

### ISSUE THREAD

**Issue by Cicko** [redux-loop/redux-loop#225]
Something very strange is happening within my reducer and I can not find out where the problem comes from.

Basically I have the same structure as the example here: https://redux-loop.js.org/docs/tutorial/Tutorial.html

and all seems good in the Networks tab of the browser inspector. I see the request and the response correctly. Even within the body of the reducer concrete switch case I can log the response and it seems like a normal response:

![image](https://user-images.githubusercontent.com/16807198/64628266-5ea59600-d3f1-11e9-97fd-08c26361168f.png)

Here you can see the reducer:
```Javascript
const reducer = (state = initialState, action) => {
    switch (action.type) {
        case CUSTOMER_FETCH_INIT:
            return loop(
                { ...state, initStarted: true },
                Cmd.run(getCustomer, {
                    successActionCreator: customerFetchSuccessfulAction,
                    failActionCreator: customerFetchFailedAction,
                    args: [action.countryId],
                }),
            );
        case CUSTOMER_SCHEMA_FETCH_INIT:
            return loop(
                { ...state, initStarted: true },
                Cmd.run(getCustomerSchema, {
                    successActionCreator: customerSchemaFetchSuccessfulAction,
                    failActionCreator: customerSchemaFetchFailedAction,
                    args: [action.countryId],
                }),
            );
        case CUSTOMER_FETCH_SUCCESS:
            return { ...state, customer: action.customer };
            
        case CUSTOMER_SCHEMA_FETCH_SUCCESS:
            console.log(action.customerSchema);
            return { ...state, schema: action.customerSchema };

        case CUSTOMER_SCHEMA_FETCH_ERROR:
            return { ...state, errror: action.error };

        case CUSTOMER_FETCH_ERROR:
            return { ...state, error: action.error };

        default:
            return state;
    }
};

export default reducer;
``` 

Where the *getCustomerSchema* is simply:

```Typescript
// Init
const CUSTOMER_SCHEMA_ROUTE = (countryId: string): string => BASE_ROUTE.concat(`/customer/schema/${countryId}`);
const getCustomerSchema = (countryId: string): Promise<Response> => fetch(CUSTOMER_SCHEMA_ROUTE(countryId));

// Successful action
const customerSchemaFetchSuccessfulAction = customerSchema => ({
	type: CUSTOMER_SCHEMA_FETCH_SUCCESS,
	customerSchema,
});

```

It updates the Redux state to an empty object:
![image](https://user-images.githubusercontent.com/16807198/64628660-176bd500-d3f2-11e9-8c53-9705f159f192.png)

And I can not find out why because as you can see where is the ``` console.log ```  it is directly before updating the state and the value is not an empty object.

I hope you might have an idea about this problem.

Thank you in advance!!

**Comment by bdwain** [comment]
i'm guessing it's because the response object is not serializable. I think redux devtools just hides things if they can't be serialized.

I would recommend processing the response in the getCustomerSchema method and resolving that promise with the actual data you want, not the response object. This abstracts more of the side effect implementation from the reducer.
