### ISSUE TITLE
Is it possibe to use redux loop in conjunction with redux-starter-kit?

### ISSUE THREAD

**Issue by on3iro** [redux-loop/redux-loop#229]
I am intrigued by [redux-starter-kit](https://redux-starter-kit.js.org/api/configurestore) and would like to use it in conjunction with redux-loop (which is still my favorite middleware for sideeffects).
However I can't seem to make it work. Here is what I've got so far:

```typescript
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider, connect } from 'react-redux'
import { combineReducers, install } from 'redux-loop'
import { configureStore, createSlice } from 'redux-starter-kit'

// Redux

const counter = createSlice({
  name: 'counter',
  initialState: 0,
  reducers: {
    increment: state => state + 1,
    decrement: state => state - 1,
  }
})

const getCount = (state: RootState) => state.Counter // => throws type error

const rootReducer = combineReducers({
  Counter: counter.reducer,
})

type RootState = ReturnType<typeof rootReducer>


// Connected component

type OwnProps = { }
type Props = ReturnType<typeof mapStateToProps> & typeof mapDispatchToProps & OwnProps

const Component = React.memo(({count, increment}: Props) => {
  return (
    <div>
      <p>Count: {count}</p>
      <button onClick={increment}>Increment</button>
    </div>
  )
})

const mapStateToProps = (state: RootState) => ({
  count: getCount(state)
})

const mapDispatchToProps = {
  increment: counter.actions.increment
}

const ConnectedComponent = connect(mapStateToProps, mapDispatchToProps)(Component)

// Setup

const store = configureStore({
  reducer: rootReducer, // => throws type error
  enhancers: (arr) => [...arr, install()]
})

ReactDOM.render(
  <Provider store={store}>
    <ConnectedComponent />
  </Provider>, document.getElementById('root')
);
```

The issue seems to be, that redux-starter-kits `conifgureStore` is unable to handle redux-loops [reducer, Cmd] type. But maybe I have just been misconfiguring the whole thing 😅 

I would highly appreciate any help with this :)

**Comment by on3iro** [comment]
oh, and there more I think about it, I realize, that these two probably wont work well together, considering the fact, that redux-starter-kit uses immer behind the scenes for updates which makes it impossible to return cmds 🤔

**Comment by fallard84** [comment]
I was trying to do the same thing and I couldn't make it work either. I keep getting the `redux-loop-immutable` error. Using `combineReducers` from `redux-loop-immutable` does not seem to help either.

**Comment by bdwain** [comment]
can you write a custom combineReducers? The built-in one is only meant for the general case. If you need anything custom, it's expected that you'll use your own.

**Comment by on3iro** [comment]
Yeah, I could try that. If I get it to work it would probably good to add a recipe for the use in conjunction with `redux-toolkit` (they recently changed their name) to the docs, because the redux team seems to heavily promote the usage of redux-toolkit.

**Comment by bdwain** [comment]
Closing this as there's nothing actionable for now. But if you come up with something useful, please make a PR

**Comment by on3iro** [comment]
Yeah, sorry - I didn't have the time to look into this, yet :(
