### ISSUE TITLE
Fix Loop generics for TypeScript

### ISSUE THREAD

**Issue by nweber-gh** [redux-loop/redux-loop#243]
The exported typings for the Loop object do not appear to be correct; the current implementation requires that an action be provided as one of the generics, even though many loops do not cause an action to be dispatched.

from `redux-loop/index.d.ts` (version 5.1.1)
```
export type Loop<S, A extends Action> = [S, CmdType<A>];
```

Example:
```
type AppState = {};
type FooAction = Action<'fooStuff'>;

function fooSideEffect(isFoo: boolean): void {
  isFoo && console.log("We got that foo.");
}

function handleMyAction(state: AppState, action: FooAction): Loop<AppState> {
  return loop(
    { ...state, foo: 'yes' },
    Cmd.run(fooSideEffect, {
      args: [true]
    })
  );
}
```

This causes an error where the return type of the function is specified.
> Generic type 'Loop' requires 2 type argument(s).

Using this signature fixes the issue but it doesn't match the actual implementation of what's happening.

```
function handleMyAction(state: AppState, action: FooAction): Loop<AppState, Action> {
```

**Comment by nweber-gh** [comment]
@laszlopandy Do you know if this is an actual issue, or am I misunderstanding the `Loop` type?

**Comment by laszlopandy** [comment]
Yes, a `Cmd.run` which doesn't specify any actions creators and doesn't use `dispatch()` doesn't need to care about the action type.
We could consider making the second type parameter to `Loop` optional. The default value could be `{}` or `any`. What happens if you specify those instead of `Action`?

**Comment by laszlopandy** [comment]
In fact `never` might work in this case as well.

**Comment by nweber-gh** [comment]
Good call. A `never` seems to work, so perhaps we should default to that. I'll add that now and report back later today about whether or not that continues to work as expected.

**Comment by nweber-gh** [comment]
So far this appears to be working as expected. We might want to consider `never` as a default in the various `Cmd` types as well. For example, `Cmd.run` also requires actions to be provided (for success and fail) even though they are optional.

Are there are commands, aside from `Cmd.action`, that *must* include an action to dispatch?

**Comment by laszlopandy** [comment]
There are only `Cmd.action`, `Cmd.run` and `Cmd.none`, the others (ie. list, map) just wrap other commands.

We can provide a second type definition for `Cmd.run` which returns `RunCmd<never>` if the action creators are not specified. But this doesn't directly solve your problem. You will still need to provide the second type argument to `Loop<S, A>` unless we make the action argument optional and I'm not sure if that's a good idea.

Maybe you want to try using this and see how it works:
```export type Loop<S, A extends Action = never> = [S, CmdType<A>];```

**Comment by nweber-gh** [comment]
`export type Loop<S, A extends Action = never> = [S, CmdType<A>];` This is exactly what I was thinking.
