### ISSUE TITLE
LoopReducer is not type safe

### ISSUE THREAD

**Issue by bdwain** [redux-loop/redux-loop#247]
@nweber-gh @laszlopandy 

I've always been confused by the type LoopReducer.

```ts
export interface LoopReducer<S, A extends Action = AnyAction> {
  (state: S | undefined, action: A, ...args: any[]): S | Loop<S, A>;
}
```

which typically leads to a reducer like this

```ts
type MyActionTypes = ActionType1 | ActionType2;

const MyReducer: LoopReducer<MyState, MyActionTypes> = (state = initState, action) => {
  switch(action.type){
    case actionTypes.TYPE_1:
      return handleType1(state, action); //infers that action is ActionType1

    case actionTypes.TYPE_2:
      return handleType2(state, action); //infers that action is ActionType2
    
	default:
	  return state; //why doesn't typescript complain about this?
  } 
};
```

The part that is confusing to me is that it defines the actions it expects to take (`A`), even though reducers need to handle all actions. How does it know what to do in the default case if you're telling it that no actions you pass will hit that default case?

It turns out that when you do a union type, typescript implicitly adds `| never` to the end of it, and that's what the type of `action` is if you reach the default case. And since it's `never`, typescript doesn't care what you do since it assumes you'll never reach that code. If you changed the default case to `return action`, typescript would not complain. It would assume it was type safe 
 because the bad return type was unreachable.

<img width="416" alt="Screen Shot 2020-06-06 at 12 37 02 AM" src="https://user-images.githubusercontent.com/3982094/83936982-5a46b780-a78e-11ea-9dce-ed06e1bc197c.png">

I looked back the PR where we added this originally (#210), and in hindsight I think this is what caused the confusion that lead to #244. We originally had one Action type in the generic, but it was for the returned actions, not the passed in actions. We started using it instead to describe the passed in actions, and we lost the parameter for the returned actions.

It looks like this was all done to allow Typescript to infer the types of the actions based on the switch statement. If we switch the type back to `AnyAction`, that no longer works and we need to cast the action before passing it to the handler.

`return handleType1(state, action as ActionType1)`

Is there some typescript magic that either of you can think of that would allow us to fix this without forcing everyone to cast the actions every time they pass them to a handler? One idea I had was if there was a utility type that was similar to union and intersection types, but a "difference" type. By that I mean for `Diff<A,B>`, it's a type that fits in `A` but not `B`. Then I would do something like this.

```ts
type MyTypesStrict = MyActionType1 | MyActionType2;
export type MyActionTypes = MyTypesStrict | Diff<AnyAction, MyTypesStrict>;
```

Then it seems the default case would no longer be `never` but instead of any type of action besides the ones I cared about. Not sure if that would allow for type inference or if it's even possible. I thought [Exclude<T,U>](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludetu) would help but it just returns `never` when I try to use it with these parameters.

If we can't figure out a solution to make it so you can actually infer the types, I think we may need to force everyone cast even though that is annoying. I think being not typesafe is not really an option in the long run (and since we have a major upgrade coming soon, now is the time do it). Though I also noticed that even if we change the type of action in LoopReducer back to `AnyAction`, you can just say 

```ts
const MyReducer: LoopReducer<MyState, MyActionTypes> = (state: MyState = initState, action: MyActionTypes) => {...}
```
and it will go back to the old behavior. Is there a way to make that a type error? Or is that an explicit override of the type system and there's nothing we can do about it?

EDIT: Typescript would complain if you tried to do something like `return 123`. But if you return something with a type of never, it won't complain because it assumes it's impossible to get there.

**Comment by bdwain** [comment]
I also am realizing now that this issue is independent of redux loop and that redux does the same thing. I'm going to look around and see if anyone has said anything about redux in general

**Comment by bdwain** [comment]
I filed https://github.com/reduxjs/redux/issues/3792

**Comment by bdwain** [comment]
the original discussion that lead to this pattern being added to redux is here https://github.com/reduxjs/redux/pull/2563#discussion_r133624376

**Comment by bdwain** [comment]
Update. we also don't complain if you forget a default statement altogether, which is probably worse.

**Comment by laszlopandy** [comment]
AFAIK TypeScript doesn't complain if you put a `default` even if the code is unreachable. I'm not sure the exact reason for this but probably it's because it is good practise, and it allows you to put an `assertNever(value)` there to force exhaustiveness. 

Regardless I agree with your concerns. The issue here is that in reality the switch should not be exhaustive. Reducers aren't necessarily supposed to handle all actions, only the ones they care about. And even if they do, redux enforces this by passing the special `'@@redux/INIT...'` at the beginning. 

So the type annotations in your example indicate to typescript "only this action type can be passed", whereas in reality anything with a `type` attribute can be passed to a reducer and it's just supposed to ignore the values it doesn't know. We can express this in TypeScript with `| { type: string }` but then TypeScript doesn't do code completion on the action type. I guess it just things because it can be any string there's no point in auto-completion.

I'm using VSCode and so far I haven't found a way to tell TypeScript that the action can be any object with a `type` while also giving auto-completion on the list of known types. If we figure that out I think we'll be close to a solution.

Regarding your other question: 
> and it will go back to the old behavior. Is there a way to make that a type error?
Yes, if in the definition of `LoopReducer` we specify that action type as `| { type: '@@redux/INIT' }`, then any function which specifies `action: MyActionType` will fail with a type mismatch.

**Comment by bdwain** [comment]
interesting idea idea with the extra fake action type! cc @nweber-gh 

```ts
export interface LoopReducer<S, A extends Action = AnyAction, B extends Action = never> {
  (state: S | undefined, action: A | {type: '@@REDUX/DONOTUSE'}, ...args: any[]): S | Loop<S, B>;
}
```

That does seem to address the issue. i like that. Are there any downsides to this solution besides the weirdness and the fact that we have a magic constant string? I feel like the only way to actually make this go wrong from a user perspective is to explicitly handle the DONOTUSE action, which is fine.

Do you want to mention this solution in https://github.com/reduxjs/redux/issues/3580 @laszlopandy ? There's an issue about this for vanilla redux too.

I spoke with @nweber-gh (we work together btw) and before you suggested this solution we were thinking it made sense to just deprecate the current `LoopReducer` type by renaming it to `LoopReducerDeprecated` and then making a new one that used AnyAction as the type (which would have type safety but no inference). This is better though so thank you for suggesting it.

**Comment by bdwain** [comment]
closing this since it's being dealt with in #244
