### ISSUE TITLE
Encourage use of "reducer creators" in documentation

### ISSUE THREAD

**Issue by ashtonwar** [redux-loop/redux-loop#58]
Without `redux-loop` making changes to the store can be quite painful - for me it meant adding constants, actionCreators, updating middleware AND the reducer. Having to make changes in a bunch of places sucks.

Now I dispatch directly to the store and only worry about the reducer. To shift the power of middleware to the reducer I've started relying on reducer creators which I use like so:

```js
import {createReducer} from '_utils/redux-plus'
import api from '_utils/api'

export default createReducer({
  GET_DATA: api('GET', '/api/data/solar-system'),
  GET_DATA_SUCCESS: (state, {payload}) => ({planets: payload}),
}, {planets: []})
```

<details> 
<summary>Implementation</summary>
```js
/**
 * An easy way to create api requests in reducers (using redux-loop)
 *
 * api('POST', '/api/endpoint')
 * api('POST', '/api/endpoint', {headers: {Authentication: 'password'}})
 * api({method: 'POST', url: '/api/endpoint', headers: {Authentication: 'password'}})
 * api((state, {payload}) => xr.post('/api/endpoint', payload))
 * api('POST', '/api/endpoint', (state) => ({counter: state.counter + 1, ...state}))
 */

import xr from 'xr'
import {loop} from '_utils/redux-plus'

const generateRequest = (config) =>
  typeof config === 'function' ? config :
    (state, {payload}) =>
      xr({[config.method === 'GET' ? 'params' : 'data']: payload, ...config})

const api = (requestConfig, updateConfig = s => _.get(s, '0', s)) => (state, action) => {
  const effect = () =>
    generateRequest(requestConfig)(state, action).then(
      response => ({type: `${action.type}_SUCCESS`, payload: response.data, meta: {response}}),
      error => ({type: `${action.type}_FAILURE`, payload: error}))
  return loop(updateConfig(state, action), effect)
}

export default (...args) =>
  typeof args[0] === 'string' && typeof args[1] === 'string' ?
    typeof args[2] !== 'function' ?
      api({method: args[0], url: args[1], ...args[2]}, args[3]) :
      api({method: args[0], url: args[1]}, args[2]) :
    api(...args)
```
</details> 

I love this pattern and think it'd be great if the documentation contained some notes about it and an example or two.

**Comment by lukewestby** [comment]
I think this might be outside the scope of what I want people to learn from using redux-loop. They can arrive at this pattern on their own, and if you want you can package your pattern up into a separate library and I'd be happy to take a look and consider recommending it in the docs

**Comment by ashtonwar** [comment]
@lukewestby I already created a library when this issue didn't receive any responses: [redux-plus](https://github.com/ashtonwar/redux-plus)
