### ISSUE TITLE
Question: What's appropriate approach to do server-side-rendering with redux-loop?

### ISSUE THREAD

**Issue by mocheng** [redux-loop/redux-loop#59]
After involving redux-loop in our code base, we found it is hard to enable server side rendering. The reason is that there is no way to let redux know that some side effect (e.g. API call) has taken place.

Basically, an `init` action is dispatched to store on HTTP request. It has to wait for that action to be fully taken care of before rendering and sending back HTML tags to browser. If side effect is triggered in actions like `thunk`, it is feasible. However, side effect is triggered by reducer in `redux-loop`. There is no way to let Redux wait for side effect to be done.

Any suggestion for this?

**Comment by mocheng** [comment]
One more thing that is in-convenient with Loop compared to thunk. Loop cannot have access to `getState`, while thunk can.

**Comment by 0xR** [comment]
Redux loop doesn't seem to solve the prefetching problem. I've been looking at https://github.com/Rezonans/redux-async-connect which does seem to solve that.

As for not having access to state you are returning your side effect from a reducer, a reducer by default has access to state.

**Comment by lukewestby** [comment]
This is something we'll figure out in a later version
