### ISSUE TITLE
Effects not being executed when multiple dispatches in the same tick

### ISSUE THREAD

**Issue by akiellor** [redux-loop/redux-loop#64]
I've been working with redux loop and have been loving it, although I think I've found a bug where if any dispatch occurs in the same tick of the event loop after a dispatch which creates an effect, the effect will not be executed.

Specifically I've experienced this with redux-form, which will dispatch actions on React lifecycle hooks (i.e. componentDidMount and componentWillRecieveProps).

I'm working on creating a minimal reproducible scenario, but comments are welcome.

I believe it has something to do with https://github.com/raisemarketplace/redux-loop/blob/master/modules/install.js#L31, although I'm still digging.

**Comment by vieron** [comment]
Same happening here!
