### ISSUE TITLE
Allow for passing dispatch to side-effect methods

### ISSUE THREAD

**Issue by bdwain** [redux-loop/redux-loop#67]
It'd be nice if the side-effects could have access to the dispatch method to dispatch arbitrary actions that are not tied to the specific task/cmd/effect they are running at the time. 

Here's a scenario where this would definitely be helpful. 

I have an API client in my project that all API requests go through. Its main job is to add auth headers to the requests, but the other thing it does is force log you out when you get a 401 back (because your token expired). With redux-loop right now I typically have to use it like this to check for the 401.

```js
function fetchItems(userid){
  return new Promise(resolve, => {
     apiClient(`/users/${userId}/items`)
       .then(rsp => {
            //process rsp
            resolve(getSuccessAction(processedRsp));
        }).catch(err => {
             resolve(err.status === 401 ? get401ErrorAction() : getItemErrorAction(err));
        });
  });
}
```

The problem is that I have to repeat this 401 logic for every request. And also there's only 1 resolved action, so you can't dispatch the item error if you need the 401 error. 

Ideally, the api client could take a dispatch method, and then just choose to dispatch a 401 error in its internal catch block before the caller handles the promise. And then the caller can also dispatch an error fetching action and not worry about if the 401 happened or not. 

That's just one scenario, but I could see it being useful pretty often.

**Comment by bdwain** [comment]
Also this might have conflicts with #66 so i'm happy to reevaluate it after that is done. I think that is a higher priority

**Comment by lukewestby** [comment]
I think the changes coming with the new `Cmd` API will make this unnecessary. You'd be able to extract that status code logic into a higher-order function and reuse it easily.

```js
const withStatusCode = (actionFor401, actionForOtherErrors) => (error) => {
  return error.status === 401 ? actionFor401() : actionForOtherErrors(error);
};

const actualErrorActionCreator = withStatusCode(actual401ActionCreator, actualOtherErrorCreator);

// ...

Cmd.promise(makeRequest, successAction, actualErrorActionCreator)
```

**Comment by bdwain** [comment]
This removes some of the repetition, but it still requires every Cmd that triggers an api request to know about the 401 functionality, instead of centralizing it in one spot. It could easily be forgotten in a scenario like that, which is my worry.

My thought was something along the lines of providing a getDispatch method (or maybe just the dispatch method directly) with something like this.

```js
Cmd.promise(makeRequest, Cmd.dispatch, successActionCreator, ...etc);

//or maybe
Cmd.promise(makeRequest, Cmd.getDispatch(), successActionCreator, ...etc);
```

this would allow our cmds to be truly generic functions that can do anything, including dispatch more actions, instead of limiting them to dispatching only one based on the return value. 

I've always viewed the actions returned by the effects as more just shorthand notation for dispatching them manually in the effect function (and in simple cases they allow you to use a generic function, like a fetchItems, from redux-loop without tying it to that), and that's kind of related to why i've pushed for the arbitrary/port/optional action in other issues.

**Comment by bdwain** [comment]
@lukewestby i was also thinking potentially about providing access to the state. Maybe via a Cmd.getState method that is passed in to a side effect method, like the dispatch example above. Basically the same things redux thunk provides to its action creators. I figure this would allow maximum flexibility.

**Comment by bdwain** [comment]
opened #82 to solve this
