### ISSUE TITLE
Prevent batching of child reducers?

### ISSUE THREAD

**Issue by tptee** [redux-loop/redux-loop#72]
Hi there,

I have two unrelated async tasks I want to run after a location change. One is quick (geolocation) while the other is slow (loading the Google Maps API). I've noticed that `combineReducers` from `redux-loop` batches all child effects. This means that even though geolocation is finished, its action won't dispatch until the Maps API loads. Is there a way to prevent batching at the top level or is there a more idiomatic solution to this problem?

**Comment by lukewestby** [comment]
For now I'm afraid there's no way around this other than to avoid using `combineReducers` and wire things together manually. I'm going to be looking into this for the next version of the library -- you are not alone in this complaint!

**Comment by bdwain** [comment]
[This enhancement](https://github.com/raisemarketplace/redux-loop/issues/56) might allow for something like that

**Comment by lukewestby** [comment]
@bdwain thank you for the reminder!! I'll put that on the list of 3.0 things (#79)

**Comment by tptee** [comment]
I worked around this by "scheduling" actions with Effects.constant and having the child reducers return the actual Effects.promise. Everything runs in parallel without being batched AFAICT. That said, an Effects.parallel without batching would be an awesome thing for 3.0 😀

**Comment by tptee** [comment]
And I guess making the combineReducers behavior configurable as well...

Also, this library is the bomb, and I'm hoping to contribute soon in the future 👍

**Comment by lukewestby** [comment]
@tptee i'm hoping to get everything to a place where we can have much more active community involvement very soon. i'm looking forward to your contributions!

**Comment by lukewestby** [comment]
I'm thinking of removing `combineReducers` altogether so this may not end up being an issue going forward
