### ISSUE TITLE
Why doesn't loop() work in "success" actions?

### ISSUE THREAD

**Issue by volkanunsal** [redux-loop/redux-loop#74]
I noticed the following behavior in `loop(..)`. Given the following:

```js
export function fetchSummary(payload = {}) {
  return fetch(`/api/dev_summary`, {
    method: 'POST',
    body: payload
  })
  .then((res) => res.json())
  .then((res) => ax.fetchSuccess(res))
  .catch(() => ax.fetchFailed())
}
```

The loop in this snippet works:

```js
[ax.fetchSummary]: (state, payload) => {
    return loop(
      state,
      Effects.promise(api.fetchSummary, payload)
    )
}
```

This snippet doesn't.

```js
[ax.fetchSuccess]: (state, payload) => {
    return loop(
      state,
      Effects.constant(ax.loadingComplete())
    )
}
```

I wonder if anyone knows why this might be happening.

Edit: When I say "works," I mean that the side effect causing action doesn't get called. In the second case, `ax.loadingComplete` never gets called. I also tried using `Effects.promise` and `Effects.batch` and had the same result.

**Comment by oviava** [comment]
I'm getting the same behaviour .. 

```js
export const getToken = (referralId) =>
  AuthService.getToken(referralId)
    .then(setToken)
    .catch(() => push('/error'));

export const setToken = (payload) => (
  { type: SET_TOKEN, payload }
);
```

and in my reducer

```js
    case SET_TOKEN:
      return loop(
        state.merge({'token': action.payload.token}),
        Effects.constant(push('/login'))
      );
```

**Comment by lukewestby** [comment]
@volkanunsal @oviava it's possible this may have had something to do with #64. Can you try your use-cases against version 2.2.2 and see if the issue is resolved?

**Comment by volkanunsal** [comment]
Yup, seems to be working. Thanks!
