### ISSUE TITLE
Monad flatMap/bind For Effects ? 

### ISSUE THREAD

**Issue by yiransheng** [redux-loop/redux-loop#76]
I have been using redux-loop for a while,  it works great! In my attempt to understand `Effects`, and trying to add a typed mental model to it, I have reach a conclusion that an `Effect` is a stacked Monad of List and Promise (Promises are impure though, a better analogy would be `Task` monad, eg. from [Data.Task](https://github.com/folktale/data.task)).

```haskell
newtype EffectOf a = EffectOf (Promise [a])
type Action = /* Plain JS Object */
type Effect = EffectOf Action
```

With this understanding, one thing critical in Monads, yet not exposed as public api is `flatMap/bind`. `Effects.lift` does serve as a `map/fmap`, though. Here's a sketch of what `flatMap` may look like:

```js
const effTypes = {
  ...,
  FLATMAP : 'FLATMAP'
}
Effects.flatMap = (eff, func) => {
  return {
    type : effTypes.FLATMAP,
    effect : eff,
    factory : func,
    [isEffectSymbol] : true
  };
}
function effectToPromise(effect) {
  switch(effect.type) {
    ...
    case effTypes.FLATMAP:
      return effectToPromise(effect.effect)
        .then(actions =>
            Effects.batch( actions.map(effect.factory) ))
        .then(effectToPromise);
  }
}
```

This allows the creation of `Effect` that "evaluates" to another `Effect`, and run the "flattend" `Effect` as normal. Here's one artificial use case for it:

```js
function getUser(action) {
  return Effects.promise(() =>
    fetch(`${apiUrl}/users/{action.payload.id}`)
      .then(user => 
          Effects.constant({ type: LOAD_SUCCESS, payload: {user} }))
      .catch(reason => Effects.none()));
}
function getProject(action) {
  return Effects.promise(() => 
    fetch(`${apiUrl}/projects/{action.payload.user.currentProjectId}`)
      .then(project => 
          Effects.constant({ type: LOAD_SUCCESS, 
              payload: {...action.payload,project} }))
      .catch(reason => Effects.none()));
}
const reducer = createReducer({
  [LOAD_DATA_START](state, action) {
    const newState = { ...state, loading:true };
    // Effects.constant serves as unit/return from Monal definition
    const eff = Effects.constant(action);
    const apiEff = Effects.flatMap(
        Effects.flatMap(eff, getUser), getProject);
    // with haskell do notation:
    // const apiEff = do {
    //   userSuccessAction <- getUser(action)
    //   getProject(userSuccessAction)
    // }
    return loop(newState, apiEff);
  }
})
```

Although, this is easier to do with just promises (have a single `Effects.promise`) the above decomposition of `getUser` and `getProject` serves as small units of Effect factories, that can be reused individually in other context - and it will be nice if `redux-loop` includes machinery to compose them.

Another example below adapted from a real use case I had:
```js
// dataReducer is a reducer that uses Effects.promise to fetch data
const decorateReducer = (dataReducer) => {
  return (state, action) => {
    const nextState = dataReducer(state, action);
    const effect = getEffect(nextState);
    if(effect) {
      const nextEffect = Effects.flatMap(effect, (act) =>
          (act.type === SUCCESS 
          ? Effect.batch([act, hideLoadingGif()].map(Effects.constant)) 
          : Effect.batch([act, showErrorModal(act.payload)].map(Effects.constant))));
      return loop(state, nextEffect);
    }
    return nextState;
  };
}


import {decorateReducer} from 'somewhere-else';

const appReducer = decorateReducer((state, action) => {
  // does just data logic here
});
```

Lastly, I have this implemented in my [fork](https://github.com/yiransheng/redux-loop/commit/15fcaa69639e3aa14a9407372d6a309f63588de8) and plan to play around with the idea a bit more (specifically how to integrate `ap` for applicative functor as well). If there's any interest in this direction of exploration, I can make a PR and some more examples.

**Comment by lukewestby** [comment]
Hey @yiransheng, I'm 100% willing to consider this as an addition to the API after getting the new version of the library released ( #79 ) after some further thought and discussion. In Elm, `Cmd`s are functors only and leave off monad or applicative behavior. I would want to spend some time evaluating what the trade-offs are and if it turns out this is a net positive then I'd be happy to include it as a minor version release. Sound good?

**Comment by yiransheng** [comment]
Sounds like a reasonable plan. Let's revisit the issue some time later :) Thanks @lukewestby.

**Comment by lukewestby** [comment]
@yiransheng redux-loop will be equipped with a proper `Task` type in the next version which is a monad with `chain` and `chainError` functions. You can use it to compose things the way you want and then perform that resulting task to get a `Cmd`

https://github.com/redux-loop/redux-loop/pull/95

**Comment by yiransheng** [comment]
Thanks @lukewestby for the good work, new API looks great!
