### ISSUE TITLE
Work with reducers from packages such as apollo stack/redux-form

### ISSUE THREAD

**Issue by wuzhuzhu** [redux-loop/redux-loop#78]
Apollo stack has to check apollo reducer in combined reducer, in redux-loop way, reducer is been transformed into immutable way. 

When apollo starts it check the apolloReducer and raise an error:

> Existing store does not use apolloReducer for apollo

The same problem might happened when using redux-form

```js
import {createStore, combineReducers} from 'redux';
import {reducer as formReducer} from 'redux-form';
const reducers = {
  // ... your other reducers here ...
  form: formReducer     // <---- Mounted at 'form'. See note below.
}
const reducer = combineReducers(reducers);
const store = createStore(reducer);

```
Is there any way to separate the imported reducer to use no immutable way?

**Comment by lukewestby** [comment]
Can you create an [SSCCE](http://sscce.org/) that illustrates the problem you're having with apollo? I don't see any immediately obvious reasons why the two shouldn't work together but I've never used apollo so I don't know how to reproduce your issue.

**Comment by Glavin001** [comment]
Also experiencing this issue with [Apollo-Client](https://github.com/apollostack/apollo-client). I'll try to make a simple demo reproducing this issue.

**Comment by Glavin001** [comment]
Related issue: https://github.com/apollostack/react-apollo/issues/87

Apollo throws the error because `getState` returns an object that does not have `reduxRootKey` (e.g. `apollo`) key: https://github.com/apollostack/apollo-client/blob/d3075a9c3181fa7e10ac290b5a6d3c8e3f291b3d/src/index.ts#L296

**Comment by lukewestby** [comment]
Let's figure this out after the next version is released if it's still an issue
