### ISSUE TITLE
Possibly set context for cmd method somehow

### ISSUE THREAD

**Issue by bdwain** [redux-loop/redux-loop#84]
it would be nice to be able to set the context of the method that a command runs somehow. The issue i ran into is that I am calling setTimeout in 1 command, returning the id and storing it so that i can later call clearTimeout.

I'd like to have `Cmd.arbitrary(clearTimeout, state.get('timeoutId')`, but that doesn't run clearTimeout in the context of window, which causes an error. So i need a useless wrapper function like this

```js
export function clearRefreshTimeout(id){
  clearTimeout(id);
}
```

i'd hate to clutter up the cmd methods with more parameters, but something to set the context would be nice

**Comment by lukewestby** [comment]
I don't think this will be an issue going forward with the new API but in that case it seems like you could just do `window.clearTimeout.bind(window)`
