### ISSUE TITLE
Symbol Support

### ISSUE THREAD

**Issue by falltodis** [redux-loop/redux-loop#86]
![image](https://cloud.githubusercontent.com/assets/7006864/17804551/bc0f6ea8-662e-11e6-8d1b-fa7658d51c02.png)

Android4.0  Start with this problem.How can I fix it

**Comment by hasseio** [comment]
`npm install es6-symbol --save`

and then at the top of your index.android.js

`import 'es6-symbol/implement';`

**Comment by falltodis** [comment]
@hasseio 3ks
