### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by OliverJAsh** [redux-loop/redux-loop#87]
Hi there! I wanted something exactly like this but I hadn't heard of redux-loop until after I had a go building something of my own: https://github.com/OliverJAsh/redux-reducer-effects/blob/master/src/main.ts

I have a few questions:
* Could this project achieve parity with the Elm API? E.g. `Task`s and `Cmd`s, like I tried to achieve in my project?
* One concern I have is how to make `Effects.promise` typesafe. I would like to use this project with TypeScript and I'm not sure how I would define the type of `Effects.promise`, as the parameters are dynamic according to the promise-returning-function passed in. If we moved to `Cmd`s (like in my example), we would have type safety here, I think.

Great project and documentation, glad to see movement in this direction! I would love to help.

**Comment by lukewestby** [comment]
Hey there! I've been super awful about maintaining this project the last several weeks (as folks like @bdwain can probably attest) but parity with elm 0.17 is definitely planned. See #79 for what's been done so far. My plan is to get moving on this again after elm-conf next week and get @bdwain and others more involved so that progress can be made on this project without blocking on me.

WRT TypeScript, I thought it would be cool to rewrite the source with it and I felt like I was fighting the type system the whole time. It's possible that there were just bugs in the compiler since I was using an alpha of 2.0. Anyway, advice on that would be appreciated if you want to open up a separate issue to share your thoughts.

**Comment by OliverJAsh** [comment]
Thanks for the fast reply!

I had a go at getting the redux-loop README example up and running using TypeScript 2 with all its goodness (no implicit any, no implicit returns, strict null checking). I think I've got something that's type safe at https://github.com/OliverJAsh/redux-loop-test/blob/master/src/main.ts. The typings can be found at https://github.com/OliverJAsh/redux-loop-test/blob/master/src/manual-typings.d.ts.

You should be able to incorporate these typings into your source code.

Notice my comments in the typings:

* `Effects.promise` can't be typed because of its dynamic arity. We can fix this by porting to Elm's API. You can see how this looks with types at https://github.com/OliverJAsh/redux-reducer-effects/blob/master/src/main.ts
* The signature of `Effects.constant` currently takes any `Action`, although I think this should be constrained to the `Action` type defined in the consumer’s reducer function, e.g. if their reducer only accepts actions of type A, we shouldn't allow actions of type B. My understanding is we will do away with the `Effects` API in favour of simple `Task`s and `Cmd`s, once we update to match Elm 0.17 so this will go away too.

I found [in my example](https://github.com/OliverJAsh/redux-reducer-effects) that `Task` and `Cmd`s are extremely simple to implement, they are just like partially applied functions.

**Comment by OliverJAsh** [comment]
I converted my example project into a real Redux enhancer, see what you think: https://github.com/OliverJAsh/redux-reducer-effects/blob/33e03bd7681b25d5a798e5ef3915a927dcfa7ee3/src/enhancer.ts#L26

**Comment by bdwain** [comment]
@OliverJAsh version 3.0 has some changes in it to be more like Cmds (disclaimer: i haven't used elm, but @lukewestby decided after making these changes that Cmds would be a more appropriate name). But a lot of work has been done in 3.0. The biggest changes are the ones discussed [here ](https://github.com/redux-loop/redux-loop/issues/66)

**Comment by lukewestby** [comment]
@OliverJAsh I took your advice along with some others and redux-loop is going to include its own `Task` API. I expect type safety is something that wouldn't be too difficult to add on later but I want to get things released first before worrying about it

Check out the changes at https://github.com/redux-loop/redux-loop/pull/95
