### ISSUE TITLE
Allow loop() to accept previously looped items

### ISSUE THREAD

**Issue by evinism** [redux-loop/redux-loop#88]
### Proposal
I'd love it if I could compose looped state such that
```
loop(loop(model, effect1), effect2)
```
would be equivalent to 
```
loop(
  model,
  Effects.batch([
    effect1, 
    effect2,
  ])
)
```

It would add a lot of syntactical flexibility, especially when I'm writing nested reducers which each have effects, and it seems to be in the same style as the rest of the interface: many methods don't care whether you supply a looped state or just a bare model, why should loop() be any different?

I'll submit a PR if you think this isn't an awful idea, or alternately if you want some solid examples, I can come up with some examples when I've got a little more free time.

**Comment by evinism** [comment]
Implemented in: https://github.com/redux-loop/redux-loop/pull/89

**Comment by yiransheng** [comment]
This is a great idea. I have been doing manual `getModel` and `getEffect` to achieve the same goal, but the api proposed here is much cleaner.

However, with the new 3.0 api and the proposed Sequence / BatchSerial Cmd types (see: #81), this might be cause a bit of issue. As there will be at least two ways of combining effects: `batch` and `sequence`. For instance:

```
export const loop = (loopOrModel, effect) => {
  if(process.env.NODE_ENV === 'development') {
    throwInvariant(
      isEffect(effect),
      'Given effect is not an effect instance.'
    );
  }

  if (!isLoop(loopOrModel)) {
    return [loopOrModel, effect];
  }
  const batchedEffect = batch([getEffect(loopOrModel), effect]);
  return [getModel(loopOrModel), batchedEffect];
}
```

vs (using newly introduced sequence function)

```
export const loop = (loopOrModel, effect) => {
  if(process.env.NODE_ENV === 'development') {
    throwInvariant(
      isEffect(effect),
      'Given effect is not an effect instance.'
    );
  }

  if (!isLoop(loopOrModel)) {
    return [loopOrModel, effect];
  }
  const batchedEffect = sequence([getEffect(loopOrModel), effect]);
  return [getModel(loopOrModel), batchedEffect];
}
```

**Comment by evinism** [comment]
Yeah, this is definitely a concern I was thinking about, and I'm throwing a wild guess that it's the reason nested loop hasn't been implemented. If loop was ever nestable, I think the least surprising thing would be for it to batch, and in the case you need some other multi-effect mechanism, you could batch it manually. Not super clean, but totally workable and probably appropriate in most cases.

The authors aren't super responsive, but I'd love more thoughts -- the problem it solves seems like a real one.

**Comment by yiransheng** [comment]
Here's a couple of ideas to address this I have came up with:

1. A third optional argument to `loop`, example:
```
    return loop(loopOrModel, Effect, combiner=Effects.batch);
```

2. A higher order function/decorator on top of `loop`

```
seqencify(loop)(loopOrModel, effect);

// implementation
sequencify = (loop) => (loopOrModel, effect) => {
   if (!isLoop(loopOrModel)) {
     return loop(loopOrModel, effect);
   }
   return loop(getModel(loopOrEffect), Effects.Sequence([getEffect(loopOrModel, effect])));
}
```
`sequencify` can be further abstracted out to take `combiner` as an argument, as an "ehancer" of `loop` - it can do things like drop original effect/cmd, implement retry and such. 

Option number 2 can be used on top of `redux-loop`, I will probably go with it in my use case.

PS: a sketch of `loop` enhancer, probably can be tweaked to be a little to resemble `redux` enhancer.
```
const enhanceLoop = (combineEffect) => (loop) => (loopOrModel, effect) => {
   if (!isLoop(loopOrModel)) {
     return loop(loopOrModel, effect);
   }
   const finalEffect = combineEffect(getEffect(loopOrModel), effect);
   return loop(getModel(loopOrEffect), finalEffect);
}
// laws for `combineEffect`:

// combineEffect(effect, Effects.none()) === effect
// combineEffect(Effects.none(), effect) === effect
```

**Comment by bdwain** [comment]
I don't think this change needs to worry about the sequence change. That change was made assuming that nested cmds are still batched. So I think it's safe to assume batch for this too.

**Comment by evinism** [comment]
For a little more concrete of an example, consider browsing through a list of images wherein we'd want to perform some sort of preloading triggered on either showing an image or destroying an image.

This branch allows for native composition of state transformations with side effects (far less verbose):
```
function ensurePreload(state){
  return loop(
    /* some synchronous state transformation that figures out which images to load*/,
    Effect.promise(/* some sort of async request that loads necessary images*/)
  )
}

// In Reducer
[SHOW_IMAGE]: (state, {payload: imageIndex}) => (
  ensurePreload(state.set('shown', imageIndex))
),
[DESTROY_IMAGE]: (state, {payload: imageToDelete}) => loop(
  ensurePreload(state.deleteIn(['collection', imageToDelete])),
  Effects.promise(destroyImage)
),
```

versus:
```
// everything else the same except for [DESTROY_IMAGE]
[DESTROY_IMAGE]: (state, {payload: imageToDelete}) => {
  const [preloadModel, preloadEffect] = ensurePreload(
    state.deleteIn(['collection', imageToDelete])
  );
  return loop(
    preloadModel,
    Effects.batch([
      preloadEffect,
      Effects.promise(destroyImage)
    ])
  );
}

```
