### ISSUE TITLE
Catch does not catch error

### ISSUE THREAD

**Issue by Arbolista** [redux-loop/redux-loop#92]
I've been using this library for a few months. I like it a lot, but one thing that has escaped me since I started using it, is that when I make an API call and update Redux state with the response, if there is a React error related to that update, my catch statements do not work.

For instance (I'm using [redux-act](https://github.com/pauldijou/redux-act) action creator functions): 

```js
import { createReducer, createAction } from 'redux-act'
const ensureAnswers = createAction('Get answers from server.'),
    answersRetrieved = createAction('Get answers data from server'),
    answersRetrievalError = createAction('Error retrieving answers from server');

createReducer({
  [ensureAnswers]: (answers_data, payload) => {
    return loop(
      answers_data,
      Effects.promise((token) => {
        let api = new SurveysApi(token);
        return api.get_answers(payload.question_ids, payload.params)
          .then(answersRetrieved) // data successfully retrieved from server
          .catch(answersRetrievalError);

      }, payload.token)
    );
  },

  [answersRetrieved]: (_answers_data, new_answers_data) => {
    return Immutable.fromJS(new_answers_data)
      .set('load_successful', true) // oops we made a mistake in handling this in a React component!
  },

  [answersRetrievalError]: (_answers_data, _res) => { // this never runs
    return Immutable.fromJS({
        load_successful: false
      })
  }

}, null);
```

```js
loop Promise caught when returned from action of type ensureAnswers.
loop Promises must not throw!

Did you forget to do one of the following?

- Call `.catch` on a Promise in a function passed to `Effects.promise`

  const asyncEffect = (val) => {
    return api.doStuff(val)
      .then((stuff) => Actions.success(stuff))
      .catch((error) => Actions.failure(error)); // <-- You have to do this!
  };

- Return an action from a `.catch` callback

  const asyncEffect = (val) => {
    return api.doStuff(val)
      .then((stuff) => {
        return Actions.success(stuff); // <-- Make sure to return here!
      })
      .catch((error) => {
        return Actions.failure(error): // <-- And return here!
      });
  };

// ...
Uncaught (in promise) ReferenceError: something is not defined(…)
```

Am I missing something here or is this the desired behavior?

Obviously this error was not caused by a 400 returned from the server, but I'd still like to be able to handle downstream errors here in the reducer - is this possible?

**Comment by bdwain** [comment]
I'm a little confused by your code, though I also am not familiar with createReducer. I don't see any default value for the state, so the first call to it seems like it will return undefined state, which redux does not allow. 

Also, you're using Effects.promise incorrectly. The promise it returns must be resolved with a redux action, even on failure (the action will probably indicate some error, but you still need to resolve it). Note that this api will change when redux loop 3.0 is released. But for 2.0, you need to resolve the returned promise with an action.

**Comment by Arbolista** [comment]
@bdwain Thanks I appreciate your prompt response.

My gist was sloppy. I'm using redux-action action creators (when called they return action object) - i updated gist accordingly.

**Comment by lukewestby** [comment]
This shouldn't be an issue the next version
