### ISSUE TITLE
Help with Testing

### ISSUE THREAD

**Issue by zachrnolan** [redux-loop/redux-loop#94]
I'm trying to follow along with the testing section in the documentation, but can't seem to get it working properly. Does anyone have any example apps with tests written for redux loop?

I'm calling an action that will kick off an Effects.promise in the reducer and I'm not seeing the state change at all. When I do a deepEqual it gives me the exact same state with this appended to the end: 

```
{
  "args": [
   {
    "mediaType": "movie",
    "mediaId": 14
   }
  ],
  "type": "PROMISE"
 }
```

Any detailed documentation or examples would be greatly appreciated, thanks!

**Comment by lukewestby** [comment]
Can you share your reducer? It'll be easier to tell what might be going wrong

**Comment by lukewestby** [comment]
Closing until we get some more information

https://github.com/redux-loop/redux-loop/blob/master/CONTRIBUTING.md
