### ISSUE TITLE
A failure in an async effect blocks other async effects from executing

### ISSUE THREAD

**Issue by volkanunsal** [redux-loop/redux-loop#96]
I would expect the asynchronously executed actions to be non-blocking in case any one of them encounters an error, but this is not the case here. In code  example below, I noticed that an error in `loginAsync` will block `loadVendorAssetsAsync`. 

Is there something I'm missing here?

``` js
const loginAsync = (): Promise<*> => new Promise((resolve, reject) => {
  return api
    .fetch('/api/me')
    .then(checkStatus)
    .then(res => res.json())
    .then((o) => ax.appLoginSuccess(o))
    .catch(() => ax.appLoginFailed());
})

...

return loop(
    state,
    Effects.batch([
      Effects.promise(loginAsync), // Error
      Effects.promise(loadVendorAssetsAsync) // Does not execute
    ])
 )
```

**Comment by chris-goodchild** [comment]
@volkanunsal - this behaviour seems the same as `Promise.all` which rejects if any error occurs. Would the answer here be to just use separate action handlers for each async operation instead of batching?

**Comment by volkanunsal** [comment]
@chris-goodchild Maybe, but I'm not using this library anymore because issues like this make it hard to reason about my program. Plus, it's been so hard to get a helpful reply from the maintainer in the past six months I've been using it. At any rate, I've switched to using the [function-tree](http://www.christianalfoni.com/articles/2016_09_11_The-case-for-function-tree) pattern and [library](https://github.com/cerebral/cerebral/tree/master/packages/function-tree#readme). I highly recommend that.
