### ISSUE TITLE
Where did the docs go?

### ISSUE THREAD

**Issue by chrisbolin** [redux-loop/redux-loop#98]
It appears that the docs aren't available on github anymore - did I miss something?

P.S. I love the work y'all have done with redux-loop! Thanks for putting it out there :)

**Comment by chrisbolin** [comment]
This commit removed the docs... https://github.com/redux-loop/redux-loop/commit/d49d7b8b3f949474269abdb414160a9b31efc16e

**Comment by lukewestby** [comment]
oh shoot! i'll put a link in the current readme to the pervious version docs. thanks!

**Comment by lukewestby** [comment]
Added to the README

**Comment by unformatt** [comment]
my 2 cents: It'd be nice to have examples, etc at the main README/url: https://github.com/redux-loop/redux-loop/

**Comment by lukewestby** [comment]
@unformatt we'll put them in as a part of finishing the 3.0 release
